name: 'Intelligent Code Review using AWS Bedrock'
description: 'Perform code review using AWS Bedrock API'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  model-id:
    description: 'Model ID'
    required: false
    default: 'Claude3'
  exclude-files:
    description: 'Exclude file list, separated by comma, e.g. [*.md,*.json]'
    required: false
# The index.js file in the intelligent-code-review action no longer needs to explicitly set AWS credentials. It will use the credentials set up by the configure-aws-credentials action
runs:
  using: 'node20'
  main: 'dist/index.js'
