name: 'Intelligent DevOps (Intelli-Ops) using Amazon Bedrock'
description: 'AI-powered GitHub Action for code reviews, PR descriptions, unit tests, and issue management using Amazon Bedrock.'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  model-id:
    description: 'Model ID'
    required: false
    # Use specific prefix sagemaker.<api url> to specify the model hosted in AWS SageMaker
    default: 'anthropic.claude-3-5-sonnet-20240620-v1:0'
  exclude-files:
    description: 'Exclude file list, separated by comma, e.g. [*.md,*.json]'
    required: false
  review-level:
    description: 'Review level'
    required: false
    default: 'detailed'
  code-review:
    description: 'Code review'
    required: false
  generate-pr-description:
    description: 'Generate PR description'
    required: false
    default: 'false'
  generate-unit-test-suite:
    description: 'Generate unit test'
    required: false
    default: 'false'
# The index.js file in the intelligent-code-review action no longer needs to explicitly set AWS credentials. It will use the credentials set up by the configure-aws-credentials action
runs:
  using: 'node20'
  main: 'dist/index.js'
